language: perl

install: echo 'nothing to install'

before_install: cpanm --notest Devel::Cover::Report::Coveralls Test::MockTime Test::Exception

script: echo -e "test:\n\tprove -l t xt" > Makefile; cover -test -report coveralls

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
