language: perl

install: echo 'nothing to install'

before_install: cpanm --notest Devel::Cover::Report::Coveralls

script: echo -e "test:\n\tprove -l" > Makefile; cover -test -report coveralls

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
