name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Build docker image
      run: docker build . --tag moment:${{ github.sha }}

    - name: Run tests in t/
      run: docker run --rm -it moment:${{ github.sha }} prove -l t/
